name: Sync SNI
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Sync
        shell: python
        run: |
          import requests, datetime
          r = requests.get("https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-SNI-RU-all.txt")
          lines = [l for l in r.text.splitlines() if l.startswith(("vless://", "vmess://", "trojan://", "ss://"))]
          # Срез с 7 строки (индекс 6) до конца
          nodes = lines[6:]
          final = [f"{n.split('#')[0].strip()}#🇷🇺 🏳️ WLUnlocker Россия (SNI) | #{i+1}" for i, n in enumerate(nodes)]
          header = f"# profile-title: Антиглушилки #1 (SNI)\n# profile-update-interval: 1\n# last-update: {datetime.datetime.now().strftime('%d.%m.%H')}\n# кол-во: {len(final)}\n"
          with open("white_sni_ru.txt", "w", encoding="utf-8") as f: f.write(header + "\n" + "\n".join(final))
      - name: Push
        run: |
          git config user.name "GitHub Actions"; git config user.email "actions@github.com"
          git add white_sni_ru.txt; git commit -m "sync: sni" || exit 0; git push
