name: Sync CIDR RU 2
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Sync
        shell: python
        run: |
          import requests, datetime
          r = requests.get("https://raw.githubusercontent.com/ByeWhiteLists/ByeWhiteLists2/refs/heads/main/ByeWhiteLists2.txt")
          lines = [l for l in r.text.splitlines() if l.startswith(("vless://", "vmess://", "trojan://", "ss://"))]
          nodes = [l for l in lines[500:] if "ru" in l.lower() or "росс" in l.lower()]
          final = [f"{n.split('#')[0].strip()}#🇷🇺 🏳️ WLUnlocker Россия | #{i+1}" for i, n in enumerate(nodes[:150])]
          header = f"# profile-title: АНТИГЛУШИЛКИ #2\n# profile-update-interval: 1\n# last-update: {datetime.datetime.now().strftime('%d.%m.%H')}\n# кол-во: {len(final)}\n"
          with open("whitelist_cidr2_ru.txt", "w", encoding="utf-8") as f: f.write(header + "\n" + "\n".join(final))
      - name: Push
        run: |
          git config user.name "GitHub Actions"; git config user.email "actions@github.com"
          git add whitelist_cidr2_ru.txt; git commit -m "sync: cidr2" || exit 0; git push
